AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Get food recall information periodically
Resources:
  FoodRecallProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
    Properties:
      Handler: lambda_function.food_recall_processor.lambda_function.lambda_handler
      Runtime: python3.13
      CodeUri: ./
      Timeout: 30
      MemorySize: 200
      Environment:
        Variables:
          DYNAMODB_TABLE: "RecallsTable"         # Environment variable for DynamoDB table
          LOG_LEVEL: "DEBUG"
          PYTHONPATH: "/var/task"                # Include path
          AWS_SAM_LOCAL: "true"
#      Events:
#        ScheduledEvent: # EventBridge rule for periodic invocation
#          Type: Schedule
#          Properties:
#            Schedule: "rate(7 days)"             # Trigger every 7 days